<a href="https://colab.research.google.com/github/Himika-Mishra/Dissertation/blob/main/Cifar10_dissertation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import keras
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from tensorflow.keras.datasets import cifar10
from keras.models import Sequential
from keras.layers import Dense, Flatten
from keras.layers import Dense, Dropout
from keras.optimizers import SGD
from keras.preprocessing.image import ImageDataGenerator
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.neural_network import MLPClassifier
from sklearn.datasets import fetch_openml
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from keras.utils import to_categorical

In [ ]:
# Load the CIFAR-10 dataset
(X_train, y_train), (X_test, y_test) = cifar10.load_data()

In [ ]:
# Normalize the pixel values to the range [0, 1]
X_train = X_train.astype('float32') / 255.0
X_test = X_test.astype('float32') / 255.0

In [ ]:
y_test.shape

(10000, 1)

In [ ]:
# Append the target arrays
y = np.concatenate((y_train, y_test))

In [ ]:
# One-hot encode the target arrays
num_classes = 10
# y_onehot = np.eye(num_classes)[y]
y_onehot = to_categorical(y, num_classes)

In [ ]:
# Splitting the encoded labels into train and test
y_train = y_onehot[:50000]
y_test = y_onehot[-10000:]

In [ ]:
num_classes = 10
y_train = to_categorical(y_train, num_classes)
y_test = to_categorical(y_test, num_classes)

In [ ]:
# Original ratio values
original_ratio_values = np.arange(0.1, 1.1, 0.1)

In [ ]:
for original_ratio in original_ratio_values:

    # Generate highly noisy images
    noise_images = np.random.random_sample(X_train.shape)
    num_original_images = int(X_train.shape[0] * original_ratio)
    original_indices = np.random.choice(X_train.shape[0], size=num_original_images, replace=False)
    original_images = X_train[original_indices]
    original_labels = y_train[original_indices]
    num_noisy_images = num_original_images  # Set the number of noisy images to match the number of original images
    noisy_labels = np.zeros((num_noisy_images, num_classes))
    X_train_current = np.concatenate([original_images, noise_images[:num_noisy_images]], axis=0)
    y_train_current = np.concatenate([original_labels, noisy_labels], axis=0)

    # Flatten the image arrays
    X_train_current = X_train_current.reshape(X_train_current.shape[0], -1)
    X_test_flattened = X_test.reshape(X_test.shape[0], -1)

    # Create and train the MLPClassifier
    model = MLPClassifier(hidden_layer_sizes=(32, 24), activation='relu', solver='adam')
    model.fit(X_train_current, y_train_current)

    # Make predictions on the test set
    y_pred = model.predict(X_test_flattened)

    # Calculate accuracy
    accuracy = accuracy_score(y_test, y_pred)

    print(f'Original Ratio: {original_ratio:.1f}')
    print(f'Test Accuracy: {accuracy * 100:.2f}%')
    
    # Fit a regular MLP classifier
    # mlp = MLPClassifier(hidden_layer_sizes=(10,8), activation='relu', solver='adam', max_iter=100)
    # mlp.fit(X_train_current, y_train_current)
    # # Accuracy Score
    # test_acc = mlp.score(X_train_current, y_train_current)
    # # print(mlp.score(X_train_current, y_train_current))
    # print(f"Test accuracy with original_ratio={original_ratio}: {test_acc}")

    # predictions
    pred = model.predict(X_test_flattened)
    print(confusion_matrix(y_test.argmax(axis=1), pred.argmax(axis=1)))
    print(classification_report(y_test.argmax(axis=1), pred.argmax(axis=1)))
    print("--------------------------------------------------")

/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


Original Ratio: 0.1
Test Accuracy: 19.14%
[[754  28  25   6   0   0  12  15 146  14]
 [533 302   2   2   4  11  17  19  63  47]
 [716  23  86  10  10  18  69  33  27   8]
 [714  16  20  38   8  61  81  18  22  22]
 [745   6  45   3  36   3 104  32  22   4]
 [636  16  21  50   7 148  53  34  25  10]
 [604   9  14  28   7   8 290  16  13  11]
 [609  11  31  13  24  32  23 216  17  24]
 [443  56   2   5   3   8   6   4 445  28]
 [501 165   2   2   4   8  21  15  74 208]]
              precision    recall  f1-score   support

           0       0.12      0.75      0.21      1000
           1       0.48      0.30      0.37      1000
           2       0.35      0.09      0.14      1000
           3       0.24      0.04      0.07      1000
           4       0.35      0.04      0.07      1000
           5       0.50      0.15      0.23      1000
           6       0.43      0.29      0.35      1000
           7       0.54      0.22      0.31      1000
           8       0.52      0.45      0

/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


Original Ratio: 0.2
Test Accuracy: 15.21%
[[840  19   5   4   2   0   8  16  94  12]
 [523 339   2   3   1   1  12  18  30  71]
 [866  18  27   8   8   0  24  35  11   3]
 [899   9   2  36   1   0  14  14  10  15]
 [891   7  13   0  18   0  12  43  12   4]
 [858  13   5  57   2   1  21  28   9   6]
 [857   6   5  17   6   0  92   6   3   8]
 [661  15   8   6   2   0   5 274  11  18]
 [582  49   1   9   0   1   3   6 318  31]
 [565 145   0   5   1   0  15  25  36 208]]
              precision    recall  f1-score   support

           0       0.11      0.84      0.20      1000
           1       0.55      0.34      0.42      1000
           2       0.40      0.03      0.05      1000
           3       0.25      0.04      0.06      1000
           4       0.44      0.02      0.03      1000
           5       0.33      0.00      0.00      1000
           6       0.45      0.09      0.15      1000
           7       0.59      0.27      0.37      1000
           8       0.60      0.32      0

/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


Original Ratio: 0.3
Test Accuracy: 18.43%
[[843   5   3   1   1   1  15  14 107  10]
 [654 215   0   1   1   2  17  10  39  61]
 [817   5  30   5   3   8  76  35  15   6]
 [789   7   4  33   2  37  92  17  10   9]
 [824   2  19   2  20   4  80  31  14   4]
 [749   6   9  31   3 107  55  28   9   3]
 [637   2   3  10   1   6 327   8   5   1]
 [675   3   1   6   6  11  26 234  13  25]
 [521  13   0   1   0  13   7   1 419  25]
 [586  81   0   3   1   7  24  20  66 212]]
              precision    recall  f1-score   support

           0       0.12      0.84      0.21      1000
           1       0.63      0.21      0.32      1000
           2       0.43      0.03      0.06      1000
           3       0.35      0.03      0.06      1000
           4       0.53      0.02      0.04      1000
           5       0.55      0.11      0.18      1000
           6       0.45      0.33      0.38      1000
           7       0.59      0.23      0.33      1000
           8       0.60      0.42      0

/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


Original Ratio: 0.4
Test Accuracy: 9.87%
[[871  19   0   0   0   0  10   3  89   8]
 [694 236   0   0   0   1   9   4  26  30]
 [925   9   0   0   0   0  31  20   6   9]
 [905  12   0  10   0   7  41  10   2  13]
 [927   4   0   0   0   0  40  16   8   5]
 [884  11   0  12   0  30  36  19   4   4]
 [827  11   0   1   0   1 149   4   1   6]
 [819  13   0   0   0   3  11 126   6  22]
 [765  37   0   1   0   1   0   0 187   9]
 [750 123   0   0   0   0   9   4  25  89]]
              precision    recall  f1-score   support

           0       0.10      0.87      0.19      1000
           1       0.50      0.24      0.32      1000
           2       0.00      0.00      0.00      1000
           3       0.42      0.01      0.02      1000
           4       0.00      0.00      0.00      1000
           5       0.70      0.03      0.06      1000
           6       0.44      0.15      0.22      1000
           7       0.61      0.13      0.21      1000
           8       0.53      0.19      0.

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
